import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/app/utils/providers/ReactQueryProvider";
import { Inter } from "next/font/google";
import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
import { ThemeProvider } from '@gravity-ui/uikit';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="en">
    <body className={inter.className}>
    <ThemeProvider theme="light">
      <ReactQueryProvider>
        <main>{children}</main>
      </ReactQueryProvider>
    </ThemeProvider>
    </body>
    </html>
  );
}
